### PR TITLE
fix some potential NPE sources

### PR DESCRIPTION
**Pull request by hannesa2**
It's related to #260 and prevent from some NPE

### CODE REVIEW

**Comment by xiphirx** [comment]
These are not really fixes. Putting these null checks everywhere is just preventing a NPE and leading to more issues while the underlying bug is still there. From a quick glance at the issue, the problem seems to be that your code is calling `dismiss()` before `show()` or `dismiss()` before the show animation is complete. 

The correct fix here would be checking whether `visible` is true in `dismiss()`, and if it is, calling `onDismiss(false)` and `ViewUtil.removeView(parent, TapTargetView.this);` immediately without starting the dismiss animations.

**Comment by hannesa2** [comment]
Thank you for the hints, I will investigate on our side.
Independent of it, this app should not crash our app, this breaks our tests

**Comment by hannesa2** [comment]
@xiphirx when you know, how to get rid of the NPE, please fix it.
Thank you !

**Comment by xiphirx** [comment]
cf27a77c0d1b80601eeeaa8aed7167d718742863 should be the correct fix.

**Pull request closed without merging**
