### PR TITLE
decrease minSdkVersion to 10 but set @TargetApi(14) for all static co…

### PR DESCRIPTION
**Pull request by McGars**
I have app with minSdkVersion 10, and i need include youre lib. I show tap only for sdk version more 14

### CODE REVIEW

**Comment by xiphirx** [comment]
If that is the case then you should set your `compileSdkVersion` to something >= 14 and guard it in your own code. It doesn't make sense to advertise this library as having a min sdk of 10 when it really doesnt.

**Comment by McGars** [comment]
Problem id my app id old and support 10, and i cant compile your lib. Write me "up minSdkVersion", but i cant. When I ibuild your lib whith 10, it fix my case

**Comment by xiphirx** [comment]
You don't need to change your min SDK. You just need to change your compile SDK.

**Comment by McGars** [comment]
Aaaa, thanx

пт, 30 сент. 2016 г., 7:24 Hilal Alsibai <notifications@github.com>:

**Pull request closed without merging**
