### PR TITLE
Add methods to set a custom container for the TapTargetView

### PR DESCRIPTION
**Pull request by leisim**
Closes issue #9

### CODE REVIEW

**Comment by xiphirx** [comment]
Hi, please base changes off of master. My `sequence` branch is not a part of the official code base, it is simply a feature branch I'm in the middle of working on. 

I will incorporate any changes that make it to master in my feature branch as appropriate.

**Comment by leisim** [comment]
OK, but I think the feature branch is much better than the master branch...

**Comment by xiphirx** [comment]
Sure, but I have not made it official or finalized it just yet, so a lot of things can still change.

**Comment by leisim** [comment]
Then I'll wait for it's release with new PRs ;)

**Pull request closed without merging**
